In [10]:
import pandas as pd

In [11]:
s=pd.Series([1,2,3,4,5])
print(s)
print(type(s))
#index
print(s[0])
print(s[3])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>
1
4

In [12]:
s=pd.Series([23,33,43,53], index=["Anna","Sara","Eram","Shifa"])
print(s)
print(s["Anna"])
print(s["Sara"])

Anna     23
Sara     33
Eram     43
Shifa    53
dtype: int64
23
33

In [13]:
s1=pd.Series([1,2,3,4])
s2=pd.Series([10,20,30,40])
print(s1+s2)

s1[0]=100
print(s1)
changed=s1.drop(0)
print(s1)
print(changed)

0    11
1    22
2    33
3    44
dtype: int64
0    100
1      2
2      3
3      4
dtype: int64
0    100
1      2
2      3
3      4
dtype: int64
1    2
2    3
3    4
dtype: int64

In [14]:
info={
    "Nmae" :["Adam","Bob","Eve"],
    "Age"  :[20,22,23],
    "CGPA" :[8.2,9.4,7.5]
}
df=pd.DataFrame(info)
print(df,type(df))
print(df.index)
print(df.columns)

   Nmae  Age  CGPA
0  Adam   20   8.2
1   Bob   22   9.4
2   Eve   23   7.5 <class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Nmae', 'Age', 'CGPA'], dtype='str')

In [15]:
df

   Nmae  Age  CGPA
0  Adam   20   8.2
1   Bob   22   9.4
2   Eve   23   7.5

In [16]:
df=pd.DataFrame([["adam",23],["Bob",34],["Eve",44]],columns=["Name","Age"])

In [17]:
df

   Name  Age
0  adam   23
1   Bob   34
2   Eve   44

In [18]:
import numpy as np
np_arr=np.array([["Adam",2,3],["Bob",5,6]])
df=pd.DataFrame(np_arr,columns=["A","B","C"])

In [19]:
df

      A  B  C
0  Adam  2  3
1   Bob  5  6

In [21]:
#csv data
df=pd.read_csv("employee_data.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [22]:
#methods
df.head(2) #start 5 data

   ID   Name  Age Department  Salary
0   1  Alice   25         HR   55000
1   2    Bob   32         IT   72000

In [23]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [24]:
import pandas as pd
#AQI data set
df=pd.read_csv("globalAirQuality.csv")
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [25]:
#selecting data
df["city"]
#for rows
df.loc[2]
df.loc[0:2]
df.iloc[2]
df.iloc[0:2]
#for rows nd column
df.loc[0,["city","aqi"]]
df.columns
df.iloc[0,0:3]
#select single vector
df.at[0,"city"]
df.iat[0,2]

'New York'

In [26]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [27]:
#filtering data
df[df["aqi"]>100]
df[(df["aqi"]>100)&(df["temperature"]>30)]
df[(df["aqi"]>100)&(df["temperature"]>30)][["city","aqi"]]
#diff between lable and index
aqi_data=df[(df["aqi"]>100)&(df["temperature"]>30)][["city","aqi"]]
aqi_data
aqi_data.iloc[0]
#aqi_data.loc[0] # will give error
#query
aqi_val=100
df.query("aqi>100 & temperature>30")[["city","aqi"]]
df.query("aqi>@aqi_val & temperature>30")[["city","aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [28]:
#cleaning data
df=pd.read_csv("raw_data.csv")
df.isnull()
df.isnull().sum(axis=1)#rows
df.isnull().sum()#columns
df.dropna()#columns
df.dropna(axis=1)#rows
df.fillna(0)
df.ffill()
df.bfill()
cleaned_data=df.copy()
age_mean=cleaned_data["age"].mean()
cleaned_data["age"]=cleaned_data["age"].fillna(age_mean)
cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [29]:
#handle duplicate val
df.duplicated() #duplicate rows
df[["country","gender"]].duplicated() #columns
#df.drop_duplicates() # removes duplicate rows
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [30]:
df.dtypes
df2=df.copy()
df2=df2.fillna(0)
df2["age"]=df2["age"].astype("int64").copy()
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [31]:
#date time
aqi_data=pd.read_csv("globalAirQuality.csv")
aqi_data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [36]:
date_str=pd.series([pd.to_datetime("2025-11-19")])
tyoe(date_str,dtype)

AttributeError: module 'pandas' has no attribute 'series'

In [32]:
#feature engineering
df2=df.copy()
df2["tax"]=df2["income"].apply(lambda x:"20%"if x>=50000 else "10%")
df2
gender_map={"Male":"M","Female":"F","Unknown":"U"}
df2=df2["gender"].map(gender_map)
df2
df.assign(new_income=df["income"]*1.1)
df["country"]=df["country"].replace("USA","United States")
df

    id          name   age        country   gender   income
0    1      John Doe  29.0  United States     Male  55000.0
1    1      John Doe  29.0  United States     Male  55000.0
2    2    Jane Smith   NaN         Canada   Female  62000.0
3    3          Alex   NaN  United States  Unknown  47000.0
4    4  Maria Garcia  34.0          Spain   Female      NaN
5    5        Li Wei  27.0          China     Male  51000.0
6    6           NaN  45.0          India   Female  73000.0
7    7    Ahmed Khan  38.0            NaN     Male  68000.0
8    8    Rachel Lee  29.0  United States   Female  62000.0
9    9   Carlos Ruiz   NaN         Mexico     Male  45000.0
10  10   Emily Davis  31.0  United States      NaN  58000.0

In [33]:
#other methods
df.rename(columns={"income":"salary"})

df_reorderd=df[["name","age","country","gender","income","id"]]
df_reorderd

            name   age        country   gender   income  id
0       John Doe  29.0  United States     Male  55000.0   1
1       John Doe  29.0  United States     Male  55000.0   1
2     Jane Smith   NaN         Canada   Female  62000.0   2
3           Alex   NaN  United States  Unknown  47000.0   3
4   Maria Garcia  34.0          Spain   Female      NaN   4
5         Li Wei  27.0          China     Male  51000.0   5
6            NaN  45.0          India   Female  73000.0   6
7     Ahmed Khan  38.0            NaN     Male  68000.0   7
8     Rachel Lee  29.0  United States   Female  62000.0   8
9    Carlos Ruiz   NaN         Mexico     Male  45000.0   9
10   Emily Davis  31.0  United States      NaN  58000.0  10

In [34]:
#sorting
df2=df.copy()
df2.sort_values("income")
df2.sort_values(["age","income"])#sorts age if age same then acc to income
df2_sorted=df2.sort_values(["age","income"])
df2_sorted.sort_index()

    id          name   age        country   gender   income
0    1      John Doe  29.0  United States     Male  55000.0
1    1      John Doe  29.0  United States     Male  55000.0
2    2    Jane Smith   NaN         Canada   Female  62000.0
3    3          Alex   NaN  United States  Unknown  47000.0
4    4  Maria Garcia  34.0          Spain   Female      NaN
5    5        Li Wei  27.0          China     Male  51000.0
6    6           NaN  45.0          India   Female  73000.0
7    7    Ahmed Khan  38.0            NaN     Male  68000.0
8    8    Rachel Lee  29.0  United States   Female  62000.0
9    9   Carlos Ruiz   NaN         Mexico     Male  45000.0
10  10   Emily Davis  31.0  United States      NaN  58000.0